### ISSUE TITLE
More informative logging when OTU has no taxid

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool-cli#20]
Look at the second line here:
```
Found isolate data for 404404
Could not find isolate data for None
Found isolate data for 463360
```
I believe this is due to the OTU having no taxid. Please provide more informative log line. For example, _Could not retrieve isolate data for <OTU name> because no taxid is defined_.

**Comment by jakeale** [comment]
I actually had made it so OTUs with no taxid don't end up in the scheduler and are effectively skipped without any logging. This might actually be a result of [some unsafe calls when fetching and handling the taxids](https://github.com/jakeale/virtool-cli/commit/58ed120d32374850002c1ee1b2c4698d6eb9256c).

If you do desire to have these logged as well I can do that.
