### ISSUE TITLE
More detailed and better formatted logging for isolate subcommand

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool-cli#21]
Current:
```
Found isolate data for 2116736
Found isolate data for 12436
Found isolate data for 192022
Could not find isolate data for 1115692
```

For each found data, write a few lines instead.

- [ ] write multiple lines for OTU for which isolate data is found
  1. first line is OTU name and taxid (lead with checkmark if success)
  2. Found <count> isolates:
  3-n. Isolate names with indentation

- [ ] write more detailed error lines as well
  1. first line is OTU name and taxid (lead with x for error)
  2. Why? None found, no taxid defined (#20)

- [ ] maintain or enhance current use of color

Example:
```
✔ Tobacco mosaic virus (12345)
  Found 2 isolates:
    - Isolate A
    - Isolate G12

✘ Rice spotting virus (678910)
  Found 0 isolates

✘ Potato streak virus (543210)
  No taxid assigned for OTU
```

**Comment by jakeale** [comment]
Do you think the found isolates should be newly found isolates that don't already exist locally or should they be all the isolates found by the fetch regardless?

**Comment by igboyes** [comment]
1. Only newly found isolates. I guess associated line should actually be: _Found 2 new isolates_
2. Yes
